### ISSUE TITLE
command "node" can't be found

### ISSUE THREAD

**Issue by sproodl** [beebls/youtube-music-history-scrobbler#1]
Thanks a lot for this program! Unfortunately when I run "start.batch" I get an error code. Roughly translated from German it says:

The command "node" is either spelled incorrectly or could not be found.

Searching manually I also couldn't find any file named such in the directories.

**Comment by beebls** [comment]
Node refers to nodejs, which is the runtime that the program runs in.
[You can install node from here](https://nodejs.org/en/), either the LTS or the Current version will work, follow the installer prompts for nodejs, and once it is installed the plugin should run fine.
